-- DSR-143: Create Fake Ratings for the Doctors

-- First we need to seed our patients table so they can write some ratings

INSERT INTO patients (patient_id,user_id) VALUES
	 (2000000080,'7e9b9a12-83c6-4da3-8bac-cb7bc0bfec20'),
	 (2000000081,'3bd69979-ca9f-48e4-8702-4bd346fa8bd6'),
	 (2000000082,'0e354796-e17d-4030-8246-b40e70ec17b7'),
	 (2000000083,'36ef9c20-0e67-4bf4-bfcf-cc40236deaf6'),
	 (2000000084,'a6cc5816-ef61-442c-950b-b78ae2cb93b6'),
	 (2000000085,'76f923df-3c8e-4f92-84da-b069e980b42e'),
	 (2000000086,'74881bf1-9c3e-4d7d-9336-75963344559a'),
	 (2000000087,'b42151c9-21c8-4e73-b87f-53b42a23ad96'),
	 (2000000088,'c7504b3c-1546-412f-9e08-4820c775fcb8'),
	 (2000000089,'f3c6d0e3-b3b2-448b-8825-75e1a1a9aa3a');

-- Then we populate our ratings table with 3 ratings per doctor

INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000001,2000000000,2000000082,5,'I would rate my experience with Doctor Walker as a 5. Doctor Walker''s charisma and approach to treatment were exceptional, making me feel at ease and in good hands. The effectiveness of the treatments received and the time management throughout the appointments were also outstanding.'),
	 (2000000002,2000000000,2000000083,5,'I had an overall positive experience with Doctor Walker. He took time to explain my condition, and his communication was thorough. I felt confident in his expertise and was satisfied with the treatment plan he prescribed.'),
	 (2000000003,2000000000,2000000088,5,'Dr. Walker''s treatment approach was highly effective, and I was completely satisfied with the care I received. I felt well taken care of and constantly updated on my progress.'),
	 (2000000004,2000000001,2000000086,2,'I would rate my experience with Dr. Shaffer as a 2. While he has great charisma and is highly skilled in his field, I have had poor communication with his assistants. I often had to wait for long periods of time for appointments, and his assistants were often unprofessional. In terms of effectiveness of treatment, Dr. Shaffer has definitely improved my condition, but I still have concerns about his approach and how he administers care.'),
	 (2000000005,2000000001,2000000087,3,'5/5. I have been treated by Dr. Shaffer for several years due to complex medical issues. Dr. Shaffer is a highly skilled, compassionate physician who takes the time to carefully listen to my concerns, explain diagnoses, and provide thorough explanations of treatment plans. Her expertise has led to significant improvements in my overall health, which I sincerely attribute to my care under her guidance.'),
	 (2000000006,2000000001,2000000088,3,'I would rate my experience with Doctor Shaffer a 3 out of 5. While he has a pleasant personality and is good at connecting with patients, his treatment approach was somewhat lacking. My condition did not improve as expected and I felt like I was not being fully heard or understood. The time management during appointments was not always efficient, causing unnecessary wait times.'),
	 (2000000007,2000000002,2000000081,2,'I would rate my experience with Doctor Gilbert a 2. While she is a knowledgeable physician, I found her to be somewhat disengaged during our appointments, and her time management has room for improvement.'),
	 (2000000008,2000000002,2000000082,3,'My experience with Doctor Gilbert was a positive one. He has a strong presence and a calm demeanor that put me at ease. As for effectiveness of treatment, my condition was successfully managed, and I feel fortunate to have had him as my doctor. One area for improvement I can suggest is the time management during appointments, sometimes I did feel a bit rushed. Overall, I would rate my experience with Doctor Gilbert a 3, and I highly recommend him.'),
	 (2000000009,2000000002,2000000088,5,'I rate Dr. Gilbert a 5. The experience was great! He was very patient, explained things clearly, and addressed all my concerns. The treatment was tailored to my specific needs, and I felt confident in his guidance. He was also timely, which made the appointments run smoothly. Overall, I highly recommend Dr. Gilbert.'),
	 (2000000010,2000000003,2000000085,4,'I would rate my experience with doctor Wilson as a 4. Although I have only had a few appointments with him so far, he has been very thorough and helpful. He listens attentively, explains things clearly, and takes time to answer any concerns or questions I may have. He has a great bedside manner and his treatment plans are very effective. I appreciate everything he has done for me so far and would highly recommend him to others.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000011,2000000003,2000000086,3,'I would rate my experience with Doctor Wilson as a 3. Although he is a highly charismatic physician, I occasionally faced long wait times in the clinic, which affected the overall quality of care. However, his expertise in diagnosing and treating my condition was top-notch, and I would recommend him to others.'),
	 (2000000012,2000000003,2000000088,3,'Exceptional doctor who is both charismatic and highly effective in treating patients. I always leave feeling better after seeing Dr. Wilson. Dr. Wilson is a competent medical professional, but there are aspects of his practice that could be improved. For instance, the wait times can sometimes be long, and his staff could work on better communication skills.'),
	 (2000000013,2000000004,2000000083,2,'My experience with Dr. Miller was satisfactory, but not exceptional. He had a good presence and seemed knowledgeable about his field. I found it easy to communicate with him, and he was efficient in diagnosing and treating my condition. I would recommend him for those looking for a capable medical professional.'),
	 (2000000014,2000000004,2000000085,3,'I rate Dr. Miller a 3. While he has a good bedside manner, I felt like he didn''t thoroughly explain certain aspects of my condition, leading to some uncertainties. Additionally, his office staff could improve their efficiency in handling phone calls and scheduling appointments.'),
	 (2000000015,2000000004,2000000086,4,'Doctor Miller is a very charismatic and effective practitioner. I felt comfortable discussing my medical concerns with him, and he provided me with clear explanations and actionable recommendations. The duration of the appointment was well-managed, and I felt like I received personalized care.'),
	 (2000000016,2000000005,2000000081,3,'I would rate Dr Garcia a 3/5. He has a good demeanor and a pleasant personality, making you feel comfortable during the visit. However, there were some communication issues during my appointment that could have been improved. Despite this, he was efficient in diagnosing my issue, providing treatment options, and addressing concerns I had. Overall, he was knowledgeable and I would recommend him to others.'),
	 (2000000017,2000000005,2000000084,3,'I would rate Dr. Garcia a 3 out of 5. While he has a pleasant manner and is easy to communicate with, I sometimes felt he was rushing through our appointments. Additionally, there were times when his explanations could be confusing or incomplete.'),
	 (2000000018,2000000005,2000000088,4,'I would rate my experience with Doctor Garcia as a 4. Dr. Garcia is a charismatic healthcare professional who effectively managed my treatment plan while providing adequate time for each patient.'),
	 (2000000019,2000000006,2000000084,2,'I rate Dr. Miller a 2 out of 5. Although she has a pleasant personality and good communication skills, her treatment approach seems too focused on quantity rather than quality. During my visits, I often felt like a number in a queue rather than a patient receiving individualized care. Consequently, I did not receive the comprehensive care I sought and had high expectations for.'),
	 (2000000020,2000000006,2000000085,1,'I was very dissatisfied with his service and attitude. He was rude, impatient, and dismissive of my symptoms. He did not examine me properly, nor did he explain his diagnosis or prescribe any medication. He seemed to have no interest in helping me or answering my questions. I do not recommend him to anyone.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000021,2000000006,2000000088,4,'Doctor Miller is an excellent physician with a strong bedside manner. She takes time to explain everything clearly and provides personalized care.'),
	 (2000000022,2000000007,2000000081,1,'I was very dissatisfied with his service and attitude. He was rude, impatient, and dismissive of my symptoms. He did not examine me properly, nor did he explain his diagnosis or prescribe any medication. He seemed to have no interest in helping me or answering my questions. I do not recommend him to anyone.'),
	 (2000000023,2000000007,2000000082,3,'As a patient, I would rate Dr. Carter a 3 out of 5. Although he had a strong presence and good communication skills, I felt that his approach to treatment was too quick and not tailored to my unique case. Additionally, there were a few instances where I felt he was not as attentive or responsive as I would like. Despite these concerns, Dr. Carter did successfully help me recover from my ailment, and I appreciate his efforts.'),
	 (2000000024,2000000007,2000000087,4,'Doctor Carter is a highly charismatic and skilled physician. Throughout my experience with her, she has consistently demonstrated excellent clinical judgment and an ability to effectively communicate complex medical information. I have been consistently satisfied with her treatment and would rate her as 4/5.'),
	 (2000000025,2000000008,2000000080,3,'I rated Dr. Dennis a 3. The experience could have been better because of a lack of communication and poor organization. The treatments he recommended were effective, and he has a pleasant personality, but his staff needs improvement in these areas to earn a higher rating.'),
	 (2000000026,2000000008,2000000082,3,'I would rate my experience with Doctor Dennis as a 3. While he has a charismatic personality and is an excellent communicator, I found his treatment approach to be somewhat lacking in effectiveness. He would often spend more time talking about his patients'' symptoms rather than providing a structured plan for treating them, which caused delays in receiving necessary care.'),
	 (2000000027,2000000008,2000000083,4,'Dr. Dennis is an excellent medical professional. He is very charismatic and engaging, which instantly puts patients at ease. His effectiveness in treating my condition was top-notch, and he always took the necessary time to answer my questions and address my concerns. I highly recommend Dr. Dennis.'),
	 (2000000028,2000000009,2000000082,1,'I was very dissatisfied with his service and attitude. He was rude, impatient, and dismissive of my symptoms. He did not examine me properly, nor did he explain his diagnosis or prescribe any medication. He seemed to have no interest in helping me or answering my questions. I do not recommend him to anyone.'),
	 (2000000029,2000000009,2000000084,4,'I rate Doctor Evans a 4. He''s a highly charismatic physician, which makes him easy to talk to. His effectiveness in treating my health issues was very good, and he took the time to answer all my questions. However, I did feel that some of his staff members could have been more efficient during the appointment, which caused a small amount of frustration. Overall, I''d definitely recommend him.'),
	 (2000000030,2000000009,2000000087,2,'I rate my experience with Doctor Evans as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000031,2000000010,2000000080,5,'I rate Dr. Tyler as a 5/5. He is a highly skilled physician, with excellent communication skills and a genuine interest in his patients. His treatment plans are effective and tailored to individual needs, and he takes time to answer questions and address concerns. I appreciate his professionalism and genuine care for my well-being.'),
	 (2000000032,2000000010,2000000083,5,'I would rate Doctor Tyler a 5. He is a very charismatic doctor who is highly effective in his treatment approach. His time management is excellent, ensuring I always feel heard and respected during our appointments.'),
	 (2000000033,2000000010,2000000086,5,'I would rate my experience with Doctor Tyler as a 5. Dr. Tyler''s charisma and bedside manner put me at ease, and he effectively answered all my questions. Additionally, he efficiently managed my time during the appointment.'),
	 (2000000034,2000000011,2000000080,4,'Dr. Hamilton is an excellent doctor who provided excellent care for my medical needs. He displayed a high level of charisma, was very effective in treating my condition, and managed his time efficiently.'),
	 (2000000035,2000000011,2000000083,3,'I would rate my experience with Doctor Hamilton a 3/5. While I found her to be a knowledgeable and experienced physician, her communication could improve. I was often left feeling uncertain about my treatment plan, which created some anxiety and uncertainty. However, she was quick to respond to calls and emails, which ultimately led to a better understanding of my condition. I believe with a little more attentiveness and effective communication, she could have received a higher rating.'),
	 (2000000036,2000000011,2000000085,4,'Doctor Hamilton has a friendly and approachable demeanor, which contributes to an overall positive experience. As a patient who primarily deals with sports medicine, I have been highly satisfied with the care I receive from Doctor Hamilton. I usually have minimal wait times when visiting this doctor, and I appreciate the efficiency of their office staff as well.'),
	 (2000000037,2000000012,2000000081,5,'I had a very positive experience with Doctor Hernandez. She is a very charismatic and attentive physician. I always felt listened to and well-cared for during my appointments. Furthermore, her expertise and knowledge helped me understand my condition and effectively manage it. I highly recommend her to anyone seeking medical care.'),
	 (2000000038,2000000012,2000000084,4,'I would rate Doctor Hernandez a 4 on a scale of 1 to 5. Although she is a very charismatic and attentive doctor, I had to wait longer than usual for my appointment, and I found that her treatments were not always effective. I did appreciate her taking the time to explain and answer my questions, though.'),
	 (2000000039,2000000012,2000000085,5,'Overall, I would rate Dr. Hernandez a 5 out of 5. He is a very charismatic physician with excellent communication skills. He takes the time to understand my concerns and thoroughly explains his recommendations. His treatment strategies are very effective, and I always feel in good hands when I''m under his care.'),
	 (2000000040,2000000013,2000000080,5,'Dr. Lyons is a 5-star doctor in my book! His charisma and bedside manner make him a great physician. His effectiveness at treating my medical condition was top-notch, and I felt very confident in his expertise. However, I did experience longer than expected wait times during my appointments.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000041,2000000013,2000000083,2,'His communication skills could improve. He sometimes seemed rushed during our appointments, and I often felt like I was not receiving the full attention of his care. Additionally, the wait times at his office were occasionally long, making it difficult to schedule follow-up appointments. I appreciate the care he provided, but I think there are other aspects of his practice he could improve upon.'),
	 (2000000042,2000000013,2000000084,5,'Dr. Lyons is an excellent physician. I give him a 5 because he is highly knowledgeable, communicates clearly, shows genuine concern for my health, and efficiently manages his time.'),
	 (2000000043,2000000014,2000000083,1,' I would rate Dr. Everett as a 1. The experience was not very satisfactory due to poor communication and inadequate treatment.'),
	 (2000000044,2000000014,2000000084,3,'I would rate my experience with Doctor Everett a 3 because while he has a strong bedside manner, his communication skills could use improvement, leaving room for better patient care. His overall effectiveness in treating my condition was satisfactory, but there were instances where delays in appointments and treatment could have been avoided with better organization. '),
	 (2000000045,2000000014,2000000085,5,'I would rate my experience with Doctor Everett as a 5. He is an excellent physician with a strong bedside manner, and I''m fortunate to have him as my primary care doctor. He takes the time to answer my questions, actively engages in my medical history, and provides thoughtful and personalized care. I appreciate his expertise and dedication to my health.'),
	 (2000000046,2000000015,2000000081,3,'I would rate my experience with Doctor Haynes a 3. While he is a charismatic and knowledgeable physician, he sometimes struggles with time management, which affects the overall experience. On the occasions where he was able to provide ample time and attentiveness, I was highly satisfied.'),
	 (2000000047,2000000015,2000000083,3,'I rate my experience with Doctor Everett as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000048,2000000015,2000000087,4,'Doctor Haynes is a charismatic and effective physician who takes the time to thoroughly examine his patients.'),
	 (2000000049,2000000016,2000000083,5,'I would rate my experience with Doctor Hebert as a 5. She is very charismatic and has excellent communication skills. The effectiveness of her treatment and time management is also top-notch.'),
	 (2000000050,2000000016,2000000086,2,'I would rate my experience with Doctor Hebert a 2. While he has a pleasant personality and good communication skills, I found his treatment approach to be lacking in effectiveness. Additionally, his time management could use improvement, as he often ran late and kept me waiting in his office for an extended period.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000051,2000000016,2000000087,4,'I would rate my experience with Doctor Hebert a 4. While he is a knowledgeable physician, I did experience some communication difficulties during our appointments. Additionally, I felt that some of his treatment recommendations were not tailored to my specific needs. Despite these issues, he did manage to help me resolve my medical concerns effectively.'),
	 (2000000052,2000000017,2000000080,5,'I would rate Dr. Miller a 5 for the following reasons: 1) His charisma and bedside manner made me feel comfortable, putting me at ease; 2) the effectiveness of his treatment has led to significant improvement in my condition; and 3) he manages his time efficiently, ensuring I receive quality care without excessive wait times.'),
	 (2000000053,2000000017,2000000081,2,'I rate my experience with Doctor Miller as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.'),
	 (2000000054,2000000017,2000000088,4,'I''d rate my experience with Dr. Miller a 4/5. She is an excellent doctor who truly cares about her patients. Her bedside manner is very comforting, and she takes the time to address each patient''s concerns. I appreciate that she is also very knowledgeable in her field, making me feel confident in her recommendations. Overall, I highly recommend this doctor.'),
	 (2000000055,2000000018,2000000080,4,'I would rate Dr. Maynard a 4 out of 5. While he is a charismatic physician, I did encounter some communication issues, which negatively impacted my overall experience. Although he was knowledgeable, effective in treating my medical condition, and managed my time well, these factors could not fully compensate for the occasional hiccups in communication.'),
	 (2000000056,2000000018,2000000081,3,'I rate my experience with Doctor Maynard as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000057,2000000018,2000000088,4,'He has a great bedside manner and made me feel very comfortable during my appointments. He was knowledgeable about my medical concerns and took time to answer any questions I had. Although I did not need any major surgeries, I appreciate his thorough approach and attention to detail. However, I did find some communication issues with the staff and scheduling appointments, leading to occasional frustration. But overall, I am satisfied with my overall experience and would recommend him.'),
	 (2000000058,2000000019,2000000080,3,'I rate my experience with Doctor Davenport as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000059,2000000019,2000000081,5,'I rate my experience with Doctor Davenport as a 5. He is a caring, knowledgeable physician who takes the time to thoroughly evaluate his patients and provides excellent treatment.'),
	 (2000000060,2000000019,2000000087,2,'I rate my experience with Doctor Davenport as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000061,2000000020,2000000080,5,'I would rate Dr. Woodard a 5 for his charismatic approach and his effectiveness in providing treatments. He is highly knowledgeable and always takes the time to answer my questions. However, I did experience some difficulty in getting an appointment and sometimes feel like I am not receiving timely care.'),
	 (2000000062,2000000020,2000000082,2,'I rate Dr. Woodard a 2 out of 5. The experience was not the best as far as communication went. I often had to wait long periods for appointments, and felt unimportant as an individual patient. Additionally, the treatment itself was not as effective as I had hoped.'),
	 (2000000063,2000000020,2000000085,4,'I rated Doctor Woodard a 4/5. I appreciated his charismatic nature and the effectiveness of his treatment. However, I felt that there were some aspects of time management that could have been improved.'),
	 (2000000064,2000000021,2000000083,2,'2/5. Doctor Gregory''s communication skills could benefit from improvement, as I sometimes had trouble understanding his instructions. However, he seems to be a knowledgeable physician with good intentions.'),
	 (2000000065,2000000021,2000000084,3,'I would rate my experience with Doctor Gregory a 3. Although he is a knowledgeable physician, his communication and bedside manner could use improvement. I often had to clarify or repeat questions, making it hard to understand his recommendations. The effectiveness of the treatment itself was satisfactory, and he did a good job in ensuring I received the necessary care. However, time management could be better as well, as I sometimes had to wait longer than I anticipated for my appointments.'),
	 (2000000066,2000000021,2000000086,4,'4/5 stars.Dr. Gregory is a highly charismatic and effective medical professional, providing excellent treatment and efficient time management.'),
	 (2000000067,2000000022,2000000080,2,'Dr. Yu is a 2-star doctor in my book. While his charisma and communication were excellent, his treatment effectiveness was average, and he sometimes struggled with time management.'),
	 (2000000068,2000000022,2000000084,2,'I would rate my experience with Doctor Yu as a 2 out of 5. While he has a good bedside manner and is knowledgeable about various medical fields, I often felt like I was not being listened to or that my concerns were not being addressed properly. Additionally, the wait times for appointments were often longer than I preferred, which also negatively impacted my overall experience.'),
	 (2000000069,2000000022,2000000087,5,'I had a wonderful experience with Doctor Yu. She is extremely charismatic, knowledgeable, and a highly skilled medical professional. Her treatment plan was tailored to my specific needs, and she took the time to explain everything clearly and answer any questions I had. I highly recommend Dr. Yu to anyone seeking exceptional healthcare.'),
	 (2000000070,2000000023,2000000080,5,'5/5. Dr. Deleon is an exceptional physician. He has excellent communication skills and provides top-notch care. He takes the time to explain everything and is always available to answer questions.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000071,2000000023,2000000081,5,'I rate my experience with Doctor Deleon a 5, as he is an incredible physician who demonstrates genuine care and concern for his patients. The treatment he provides is effective, and he always takes the time to answer any and all questions I may have.'),
	 (2000000072,2000000023,2000000083,4,'Dr. Deleon is a highly charismatic physician who puts his patients at ease immediately. As a general practitioner, he is well-versed in a wide range of medical issues, which makes him an excellent diagnostician. Although his treatment plan can sometimes be a bit aggressive, it is often effective in providing long-term relief. Overall, I highly recommend Dr. Patterson, and would rate both the physician and the experience 4 out of 5.'),
	 (2000000073,2000000024,2000000084,3,'I would rate Dr. Hess a 3. While he has a good bedside manner and is easy to communicate with, I felt there could be more efficiency in his practice. The wait time for appointments is often long, and I sometimes felt overlooked during my visits. Overall, I appreciate his expertise and knowledge of medicine, but there is room for improvement in his patient care approach.'),
	 (2000000074,2000000024,2000000086,4,'As for effectiveness of the treatment, he has a thorough approach, addressing all my concerns, which gives me confidence in his competence. However, I did find some delays in appointment scheduling, which could be improved. Time management can sometimes be a challenge during appointments, and I feel like I had to wait a little longer than I would have liked. Nonetheless, I''m overall pleased with my experience and would recommend him to others.'),
	 (2000000075,2000000024,2000000088,3,'I would rate Doctor Hess a 3 out of 5, with the following explanation: Doctor Hess''s clinical knowledge and experience are impressive, and they have a calm, reassuring demeanor. However, they might be perceived as slightly disorganized, as there was a delay in getting test results and the appointment scheduling process could be more efficient. The wait time in the clinic could also be reduced to better utilize patients'' time.'),
	 (2000000076,2000000025,2000000082,2,'I would rate my experience with Doctor Jones as a 2. While the doctor has a good amount of knowledge, their communication and interpersonal skills could stand improvement. On the positive side, they were able to accurately diagnose my condition and recommend an effective treatment plan.'),
	 (2000000077,2000000025,2000000083,5,'Dr. Jones is a 5-star doctor! She is very charismatic, and her thorough examination and treatment has been extremely effective. The time management during my appointments was flawless, and I always felt well taken care of.'),
	 (2000000078,2000000025,2000000088,4,'I would rate Doctor Jones a 4 out of 5. Although he was very charismatic and made me feel comfortable during our sessions, his treatment approach was somewhat lacking, leading to longer wait times. Additionally, there was sometimes a communication breakdown, causing delays in the effectiveness of the treatment plan.'),
	 (2000000079,2000000026,2000000081,4,'I rate Dr. Mcclure a 4 out of 5. While he has a strong presence, his communication and bedside manner could use improvement. Overall, the efficacy of his treatment and the time he spends with me has been excellent.'),
	 (2000000080,2000000026,2000000084,4,'I rate Dr. McClure a 4 out of 5. Although he is a skilled physician, I had a slightly disappointing experience with him during my recent visit. While he was knowledgeable and communicated effectively, I did not have the same level of rapport with him as I did with my previous primary care physician. Furthermore, his treatment plan fell just short of meeting my expectations, and his time management skills could have been more efficient.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000081,2000000026,2000000086,3,'Doctor McClare is an amazing physician. She has a wonderful personality and makes me feel very comfortable when discussing personal health concerns. Her knowledge and experience in the medical field are top-notch. However, there has been some inconsistency with appointment scheduling and communication regarding test results. I would highly recommend her, but improvements in these areas are needed to achieve a perfect rating.'),
	 (2000000082,2000000027,2000000084,2,'I would rate Doctor Martin a 2. Doctor Martin has a great personality, which made communication and trust easy. However, I feel there could be better management of time during appointments. Treatment options discussed were comprehensive, but I sometimes felt rushed.'),
	 (2000000083,2000000027,2000000085,4,'I would rate my experience with Doctor Martin as a 4. I had a positive experience with him because he is a highly skilled physician and provided excellent care for my medical needs. He was very professional and courteous, took the time to answer my questions, and offered helpful advice. I would highly recommend him to anyone seeking medical attention.'),
	 (2000000084,2000000027,2000000088,2,'I rate Dr. Martin a 2/5. Although he had a strong presence and seemed very knowledgeable, I found his time management and communication skills to be lacking. In several appointments, he was either late or didn''t spend enough time with me, making it difficult to fully discuss my health concerns. Furthermore, he seemed to rush through each appointment, which made me feel unimportant as a patient.'),
	 (2000000085,2000000028,2000000081,2,'Dr. Baldwin is a caring and knowledgeable physician. I appreciate her thorough examination and the time she spends explaining my medical concerns. However, on several occasions, her time management was a bit chaotic, making it difficult to schedule follow-up appointments.'),
	 (2000000086,2000000028,2000000083,3,'Dr. Baldwin is a competent doctor who I have had a positive experience with; however, I believe there are room(s) for improvement in terms of time management and communication. During my appointments, he was always informative, helpful, and approachable.'),
	 (2000000087,2000000028,2000000084,4,'As a medical professional, I appreciate Dr. Baldwin''s thorough examination, as well as her warmth and compassion towards me as a patient. I rate my overall experience with her as a 4 out of 5.'),
	 (2000000088,2000000029,2000000083,4,'I rated Dr. Edwards a 4 because they were very professional, had a great bedside manner, and were very knowledgeable. I was very satisfied with their approach to my treatment.'),
	 (2000000089,2000000029,2000000084,2,'Doctor Edwards is a charismatic physician, and they provided effective treatment for my condition. The time they spent with me was also good. However, I feel that their approach could be more personalized, as they mainly focused on the physical aspect of the issue and didn''t take into account some of my emotional concerns.'),
	 (2000000090,2000000029,2000000085,4,'Doctor Edwards is a very charismatic physician, which definitely adds to the positive experience. However, the wait times for appointments are occasionally long, which could be improved. Overall, an excellent doctor.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000091,2000000030,2000000084,3,'I would rate Doctor Blair a 3. Although he has a calm and reassuring demeanor, his communication skills leave a lot to be desired. On multiple occasions, important information was not communicated effectively, causing unnecessary anxiety and delays in the treatment process.'),
	 (2000000092,2000000030,2000000086,4,'4/5 - The doctor is a highly skilled professional who takes a thorough approach to patient care. Although I was pleased with the effectiveness of the treatment, I feel that Doctor Blair could have been more timely in responding to my inquiries and requests.'),
	 (2000000093,2000000030,2000000087,4,'My overall experience with Doctor Blair rated a 4. The charisma and effectiveness of the treatment were excellent. However, there was a slight delay in the time management during appointments.'),
	 (2000000094,2000000031,2000000081,3,'I rate Doctor Robertson a 3. Although she is a skilled physician, I felt like her communication could be more effective; often, I left her appointments feeling unclear about my treatment plan.'),
	 (2000000095,2000000031,2000000082,2,'I rate my experience with Doctor Robertson as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.'),
	 (2000000096,2000000031,2000000088,5,'I would rate my experience with Doctor Robertson as a 5. Doctor Robertson is a highly charismatic and skilled physician. Their effective treatment methods and timely management of appointments have been instrumental in my improved health.'),
	 (2000000097,2000000032,2000000084,5,'Doctor Reed is an outstanding physician! He listens carefully and addresses any concerns I may have. His explanations of medical conditions and treatment options are thorough and understandable, and he always takes ample time to answer my questions without making me feel rushed.'),
	 (2000000098,2000000032,2000000085,5,'Excellent Doctor Reed provides excellent treatment and has an excellent bedside manner, making me feel very comfortable during our interactions. The time spent with him is well-organized, efficient, and informative.'),
	 (2000000099,2000000032,2000000087,4,'I would rate Dr. Reed a 4/5. She is an excellent doctor with a warm and caring personality, and she is very knowledgeable in her field. Her treatment plans are always thorough and effective, and she always spends time with me to ensure that I fully understand my condition and the necessary steps to take care of it. However, I did experience a bit of frustration with wait times in her office, though this may be related to the high demand for her services.'),
	 (2000000100,2000000033,2000000083,4,'Dr. Holland is an excellent physician who I rate as a 4 on a scale of 1 to 5. His charismatic personality and vast medical knowledge instantly put patients at ease. He is highly effective in providing comprehensive and timely care for his patients. In terms of time management, Dr. Holland is well-organized and efficient, ensuring that patients are seen in a timely manner while also receiving the necessary attention and care.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000101,2000000033,2000000084,4,'My experience with Doctor Holland was exceptional; he has a great bedside manner and made me feel at ease. His effectiveness in diagnosing and treating my medical condition was excellent. He took the time to explain things thoroughly and was always available for my questions or concerns. Overall, I''d highly recommend him.'),
	 (2000000102,2000000033,2000000088,4,'Doctor Holland is a very charismatic and skilled physician who takes the time to listen to his patients and develop personalized treatment plans. However, I would rate his effectiveness as slightly less than 5 due to a few instances where he seemed to dismiss my concerns and provided inadequate follow-up care. The overall experience was still positive, but I would recommend seeking another opinion if faced with a more complex medical issue.'),
	 (2000000103,2000000034,2000000084,4,'I would rate Dr. Hill a 4 out of 5. The doctor was personable and communicated well, which made the appointment pleasant and efficient. However, their efficiency might have been impacted by the volume of patients they saw that day. I hope to have had a more individualized experience during my follow-up visit.'),
	 (2000000104,2000000034,2000000085,5,'I rate Dr. Hill a 5/5. Dr. Hill is a charismatic and compassionate physician, who always takes the time to listen to my concerns and provides me with clear explanations. She is very knowledgeable and effective in her treatments.'),
	 (2000000105,2000000034,2000000087,3,'I rate my experience with Doctor Hill as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000106,2000000035,2000000082,5,'Doctor Smith is an exceptional physician with a strong presence and a genuine passion for helping patients. His charisma and communication skills make him a top-notch healthcare professional. His effectiveness in treating my condition and managing my overall health was stellar. I couldn''t have asked for better care.'),
	 (2000000107,2000000035,2000000084,5,'I rate Doctor Smith a 5. His charismatic personality and efficient approach to treatment greatly impressed me. Furthermore, the time management skill that he demonstrated throughout the appointment ensured a smooth and efficient process.'),
	 (2000000108,2000000035,2000000087,5,'I would rate Doctor Smith a 5 because he was very charismatic, efficient in his work, and maintained good time management. He effectively communicated with me throughout my treatment and provided me with tailored treatments for my specific needs.'),
	 (2000000109,2000000036,2000000081,3,'I rate Doctor Hoffman as a 3/5 due to his charisma and effectiveness in treating my condition. He is knowledgeable and communicates clearly, making me feel comfortable during my appointments. However, there were some instances where his time management could be improved, causing delays in treatment.'),
	 (2000000110,2000000036,2000000086,5,'Dr. Hoffman is a 5 for me. My experience with him has been positive and effective. His charismatic personality and his ability to quickly assess and diagnose my medical concerns make him a skilled physician. Moreover, he is always thorough in his explanations and takes the time to answer my questions. Overall, I''d recommend him highly for anyone seeking a top-notch medical professional.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000111,2000000036,2000000087,4,'4/5 - I had a positive experience with Doctor Hoffman. She is a charismatic and competent medical professional, and I highly recommend her.'),
	 (2000000112,2000000037,2000000080,4,'I would rate Dr. Avila a 4. While she has a great demeanor and is a knowledgeable physician, her time management seems to be a bit chaotic. Sometimes I had to wait for a long time in her office.'),
	 (2000000113,2000000037,2000000083,5,' Doctor Avila is a highly charismatic, competent, and organized medical professional. His approach to patient care is thorough, efficient, and effective, making him a top-notch physician. I have been fortunate to have him as my medical provider, and I highly recommend him.'),
	 (2000000114,2000000037,2000000085,5,'I would rate Doctor Avila a 5. My experience was positive due to her excellent listening skills and empathy, along with her knowledge and effectiveness in treating my health concern.'),
	 (2000000115,2000000038,2000000082,5,'She has a great personality and is very charismatic. Throughout my entire treatment, Dr. Richardson was approachable and always made me feel comfortable talking to her. Additionally, her effective treatment plan has me feeling much better. I have been able to manage my pain more effectively and am now walking more regularly as a result of her treatment. I would highly recommend her to anyone seeking relief from physical pain.'),
	 (2000000116,2000000038,2000000083,3,'I would rate Dr. Richardson a 3 out of 5. While he has a pleasant personality and is a skilled surgeon, I experienced some communication issues and felt that certain aspects of my treatment were not as effective as they could have been.'),
	 (2000000117,2000000038,2000000088,4,'I would rate my experience with Doctor Richardson as a 4. While he is a knowledgeable and experienced physician, I feel that his communication style could be improved. I often had to wait longer than necessary for appointments, and I sometimes felt rushed during our conversations. Nonetheless, he effectively treated my medical condition, and I am thankful for that.'),
	 (2000000118,2000000039,2000000082,5,'I have a 5-star rating for Doctor Roberts. Throughout my experience with him, he consistently displayed a high level of professionalism and care. His charisma and excellent communication made me feel comfortable during our appointments. Not only is he an excellent physician, but he also manages his time very well, ensuring that each patient is given the attention and care they deserve.'),
	 (2000000119,2000000039,2000000085,4,'I would rate Doctor Roberts a 4 out of 5. Their charisma and communication skills were excellent, and they were highly effective in treating my condition. However, I had to wait for a long time in the clinic, which I found quite disorganized and unprofessional.'),
	 (2000000120,2000000039,2000000088,2,'2/5. Doctor Roberts has a high level of charisma, making it easy to communicate with her. Although she is effective in treating patients, I had some concerns about the timeliness of her appointments. At times, I had to wait for over an hour to be seen, which I found to be a bit disconcerting. However, I would still recommend her for the quality of care she provides.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000121,2000000040,2000000082,2,'2 - I have seen better doctors in my time; however, Dr. Miller is competent and provides adequate care. My issue may have been with scheduling and the wait time to get in to see him.'),
	 (2000000122,2000000040,2000000085,3,'I would rate my experience with Doctor Miller a 3. Although she is a knowledgeable physician, her approach to patient care could be more effective in certain situations. Her communication style could be improved, and her time management could be more efficient. I would like to see a greater emphasis on patient education and personalized treatment plans, as this could lead to a better overall experience.'),
	 (2000000123,2000000040,2000000088,5,'Doctor Miller is a 5 star physician; his charisma and effectiveness of the treatment greatly exceed any expectations I had. He''s a very organized and timely professional, ensuring that each patient has his undivided attention during appointments. Highly recommend!'),
	 (2000000124,2000000041,2000000080,3,'I would rate my experience with Doctor Patterson a 3 out of 5. Although he is a highly knowledgeable physician, I felt that his communication skills could improve. On several occasions, he seemed to rush through our appointment, leaving me feeling unsatisfied. I also had to wait longer than anticipated for test results. However, he did provide effective treatment for my condition, so I cannot complain too much.'),
	 (2000000125,2000000041,2000000081,2,'I would rate my experience with Doctor Patterson as a 2 out of 5. While Doctor Patterson has a charming personality, he lacks the clinical competence needed to effectively diagnose and treat patients. The treatment I received lacked in effectiveness, and the time management during my appointments was not efficient, leaving me feeling undervalued.'),
	 (2000000126,2000000041,2000000085,4,'I rate my experience with Doctor Patterson as a 4 out of 5. Doctor Patterson''s charismatic personality and strong communication skills made him easy to approach, and I always felt comfortable discussing my concerns with him. He was also very effective in treating my specific medical condition. However, I did find some time management issues during my appointments, as sometimes I had to wait longer than expected.'),
	 (2000000127,2000000042,2000000080,5,'I would rate my experience with Doctor Brown a 5. Doctor Brown is a charismatic and knowledgeable physician who took the time to answer my questions and concerns. Under his care, I was able to develop an effective treatment plan that has improved my overall health.'),
	 (2000000128,2000000042,2000000085,3,'I would rate Doctor Brown a 3 out of 5. Although he has a pleasant demeanor and a strong work ethic, I have had some concerns with the effectiveness of his treatment methods and the time he takes to address my concerns.'),
	 (2000000129,2000000042,2000000087,2,'I would rate my experience with Dr. Brown as a 2. Although he has a charming personality and seems knowledgeable in his field, his communication skills and efficiency in treating patients leave much to be desired. During my visits, I often had to wait for extended periods of time, and the quality of his treatment seemed to vary from appointment to appointment. He is a competent physician, but I believe there are other doctors in his field who better align with my expectations.'),
	 (2000000130,2000000043,2000000081,3,'The treatment plan did not seem tailored to my specific needs, and I sometimes felt neglected as a patient. However, I acknowledge that these concerns might be related to my individual case, and I appreciate his team''s work in ensuring a smooth recovery process.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000131,2000000043,2000000082,4,'I rate Doctor Burke a 4 out of 5. His charismatic personality and effective treatment of my medical condition have been top-notch. Despite a busy schedule, he always takes the time to answer my questions and address my concerns patiently. I highly recommend him as a healthcare professional.'),
	 (2000000132,2000000043,2000000083,5,'I highly rate my experience with Doctor Burke as a 5. Throughout my entire treatment process, he has consistently demonstrated exceptional clinical skills, a warm and compassionate demeanor, and excellent communication. His expertise and guidance have been instrumental in the successful completion and recovery from my medical procedures.'),
	 (2000000133,2000000044,2000000080,4,'I would rate my experience with Doctor Rosales as a 4/5. The doctor has a great personality and is very charismatic, which made me feel comfortable during my appointments. Additionally, the effectiveness of the treatments I received were top-notch. However, I feel that the time management could be improved as I often had to wait for a long time in the waiting room. Nonetheless, I highly recommend Dr. Rosales.'),
	 (2000000134,2000000044,2000000082,4,'I would rate my experience with Doctor Rosales as a 4. While she is a highly skilled physician, I feel her communication approach could be more effective. I often found myself unsure about the specific actions and recommendations she provided. I had to constantly clarify information, which took up extra time during my appointments.'),
	 (2000000135,2000000044,2000000088,2,'I would rate Doctor Rosales as a 2 on a scale of 1 to 5 because my experience lacked proper communication, empathy, and follow-up care.'),
	 (2000000136,2000000045,2000000080,5,'My experience with Doctor Keith exceeded my expectations. He is a very charismatic and compassionate healthcare professional who provided excellent treatment for my medical needs. He is highly effective in his role and consistently goes above and beyond to make sure his patients are comfortable and satisfied. Additionally, he always manages his time efficiently, so patients are seen promptly and have minimal wait times.'),
	 (2000000137,2000000045,2000000081,3,'I rate my experience with Doctor Keith as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000138,2000000045,2000000085,2,'I rate Dr. Keith as a 2. Overall, his charisma and communication were excellent, as I always felt well-informed and confident in his care. However, I did experience some challenges with the time he took to address my concerns and provide treatment recommendations. On a couple of occasions, I felt like my concerns were not fully addressed, and I had to request additional information or follow-up appointments to feel comfortable with my care.'),
	 (2000000139,2000000046,2000000082,3,'My experience with Dr. Young as a 3/5 rating. He has a charismatic personality that instantly makes you feel comfortable, which is crucial when dealing with anxiety. His effectiveness in treating my condition was excellent, and he was always available to answer any questions I had. However, I felt there could be better communication on the progress of my treatment plan, as well as more efficient time management during our appointments.'),
	 (2000000140,2000000046,2000000083,4,'I would rate my experience with Doctor Young a 4. Although he is a brilliant doctor, he sometimes lacks time management skills and can be a bit unpredictable in his approach. However, his knowledge and experience have greatly improved my health, making him an excellent medical professional.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000141,2000000046,2000000088,2,'I would rate my experience with Doctor Young as a 2. While I appreciate her charisma and the time she takes to answer my questions, the effectiveness of her treatments left me feeling underwhelmed. I am still unsure about the treatment plan she has proposed, and I would have liked more guidance and clarity around the expected outcomes and potential risks.'),
	 (2000000142,2000000047,2000000081,3,'I would rate my experience with Doctor Glenn as a 3. Although he has a great personality and is knowledgeable, I often had to wait in long lines for my appointments and felt that the treatment recommendations could be more tailored to my specific needs.'),
	 (2000000143,2000000047,2000000082,2,'I would rate my experience with Doctor Glenn a 2. Although he has a strong presence, and I found him to be knowledgeable and thorough in his examination, I did feel that the duration of the appointment was a bit too long. It seemed to be an excessive amount of time spent, considering my particular issue was relatively simple and straightforward.'),
	 (2000000144,2000000047,2000000085,4,'Dr. Glenn has been a fantastic doctor throughout my pregnancy. He is very professional, charismatic, and has been an excellent communicator. I''m extremely happy with the care he has provided, and wouldn''t hesitate recommending him to my friends.'),
	 (2000000145,2000000048,2000000081,3,'3/5. I''d rate my experience with Dr. Weeks as a 3 because, while he is a charismatic physician, I didn''t feel he was particularly effective in treating my condition, and his time management could use improvement.'),
	 (2000000146,2000000048,2000000085,5,'Doctor Weeks is an exceptional physician. His calm and professional demeanor puts patients at ease, while his expertise and extensive knowledge make him highly effective. His treatment plans are tailored and effective, and he always ensures that his patients receive the necessary care in a timely manner. A+.'),
	 (2000000147,2000000048,2000000088,2,'I would rate my experience with Dr. Weeks a 2 out of 5. Doctor Weeks is a charismatic figure and I found him very engaging during our initial consultation. He explained the treatment plan very clearly and I felt confident in his abilities to help me improve my dental health. However, after a few weeks of treatment, I felt like the frequency and duration of the appointments were not meeting my expectations.'),
	 (2000000148,2000000049,2000000080,3,'I rate Doctor Powell as a 3. The experience overall was good, but I felt there were areas for improvement in terms of communication and efficiency. Doctor Powell was friendly and knowledgeable, but I often had to wait longer than expected for appointments. Treatment was effective, but I would like to see more attention paid to my individual needs and concerns. Overall, I''d recommend him; however, there is room for improvement in these areas.'),
	 (2000000149,2000000049,2000000081,3,'I rate my experience with Doctor Powell a 3. While he is a charismatic physician, his communication skills could improve. The effectiveness of his treatment approaches may vary, and I feel that he could manage time more efficiently.'),
	 (2000000150,2000000049,2000000085,5,'I would rate my experience with Doctor Powell as a 5. Doctor Powell''s charisma and professionalism instantly made me feel at ease in their presence. Their effectiveness in treating my condition was top-notch, and I am thankful for the time and effort put into my care.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000151,2000000050,2000000080,2,'I rate my experience with Doctor Dougherty as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.'),
	 (2000000152,2000000050,2000000084,4,'I rate Dr. Dougherty a 4/5 for both charisma and effectiveness in treatment. However, I had to rate the time management aspect lower due to a significant wait time during my appointments.'),
	 (2000000153,2000000050,2000000087,3,'I rate my experience with Doctor Dougherty as a 3. He provides decent medical care, but I felt that he could improve in terms of listening to his patients and explaining treatment options more thoroughly.'),
	 (2000000154,2000000051,2000000081,4,'4/5. Dr. Lloyd is an excellent doctor with a strong bedside manner and great communication skills. He is highly knowledgeable and has great experience in his field. However, I would rate his treatment effectiveness slightly lower due to some delays in appointment scheduling.'),
	 (2000000155,2000000051,2000000083,5,'I rate Doctor Lloyd as a 5, mainly due to his excellent communication skills and his thorough approach in treating my condition. He always took the time to answer my questions and explained everything clearly. Additionally, I appreciate the fact that he is a highly experienced doctor, giving me the utmost confidence in his expertise.  The only room for improvement would be in terms of wait times, as sometimes I had to wait longer than I would have liked.'),
	 (2000000156,2000000051,2000000084,5,'I would rate Doctor Lloyd a 5. My experience with him was positive due to his excellent communication skills and thorough approach to diagnosing and treating my medical issue. He provided detailed explanations and demonstrated high-quality care. I was impressed with his professionalism and would highly recommend him.'),
	 (2000000157,2000000052,2000000080,2,'I would rate my experience with Doctor Johnson as a 2. While he has a pleasant demeanor and provided efficient medical care, I felt that his communication skills could improve. As a result, it was often difficult to understand the treatment plan he recommended. Additionally, I had to wait longer than expected for appointments and felt that my concerns were not always addressed adequately.'),
	 (2000000158,2000000052,2000000084,4,'I would rate my experience with Doctor Johnson a 4 out of 5. Doctor Johnson''s bedside manner and approach to treatment were highly effective, leaving me feeling well taken care of. Additionally, they were able to diagnose and treat a complex medical issue with efficiency and professionalism. However, I did experience some frustration with the time spent waiting in the office for appointments, which I believe could be better managed to minimize patient frustration.'),
	 (2000000159,2000000052,2000000088,5,'I rated Doctor Johnson a 5 because he has exceptional charisma and communication skills. He thoroughly explains everything, making me feel comfortable and well-informed throughout the process. Additionally, he demonstrated great effectiveness in treating my condition, and his treatment plan was tailored to my specific needs. Lastly, he always had plenty of time for me during each appointment, making it easy to schedule, and reducing my overall wait time.'),
	 (2000000160,2000000053,2000000081,4,'My experience with Dr. Martinez was a positive one overall. He has a charming and personable demeanor, which made it easy to feel comfortable during our interactions. The effectiveness of his treatment plan was also impressive, as he addressed my concerns, provided helpful advice, and tailored his approach to my unique needs. I appreciated his thorough time management, which kept my appointments on schedule and minimized wait times.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000161,2000000053,2000000082,3,'My experience with Doctor Martinez is a 3/5. Doctor Martinez has an excellent clinical knowledge and a great bedside manner. They explained my condition clearly and patiently. However, their time management could be more efficient. I sometimes had to wait longer than I expected.'),
	 (2000000162,2000000053,2000000086,4,'I rate Dr. Martinez a 4/5. He has a great bedside manner and made me feel at ease during my appointments. His treatments were effective and he always took the time to answer my questions. However, there was one time where the wait time for an appointment was a bit long. Overall, I would highly recommend Dr. Martinez.'),
	 (2000000163,2000000054,2000000086,4,'I rate Dr. Davidson a 4 out of 5. His bedside manner was excellent, and he was very personable. I felt comfortable discussing my medical concerns with him. The treatment he provided was effective, and he was timely in responding to my questions. One thing I would suggest is to improve the efficiency of the waiting room process.'),
	 (2000000164,2000000054,2000000087,5,'Dr. Davidson is a 5-star physician in my book. He has a charismatic personality, and his communication skills are excellent. He listens carefully to my concerns and explains complex medical issues in simple terms. His treatment has been effective and efficient, and I always feel well taken care of when visiting him.'),
	 (2000000165,2000000054,2000000088,4,'The patient reported that Dr. Davidson was very patient-oriented and took time to answer all of their questions and concerns. Additionally, their appointments were typically scheduled on time and they never had to wait for too long. Overall, the patient was very happy with their experience and would highly recommend Dr. Davidson to others.'),
	 (2000000166,2000000055,2000000081,2,'I would rate Doctor White a 2. Although he is a charismatic and knowledgeable doctor, I feel that the time management and effectiveness of the treatment could be improved.'),
	 (2000000167,2000000055,2000000087,5,'My experience with Dr. White was a positive one, earning a rating of 5. I appreciated his calm and gentle demeanor, which made me feel comfortable during our interactions. His knowledge and expertise were evident in the effective treatment plan he tailored for me. He always took time to answer my questions, providing me with a clear understanding of my health concerns. '),
	 (2000000168,2000000055,2000000088,4,'I would rate my experience with Doctor White a 4/5. Doctor White''s charisma and approach to treatment were very professional, and I felt well taken care of throughout my appointments. The effectiveness of the treatment plan was very satisfactory, and I am confident in the progress I have made under their care. I also appreciate the time they took to answer my questions and address my concerns.'),
	 (2000000169,2000000056,2000000081,4,'I would rate my experience with Doctor Williams a 4. Although he has excellent clinical knowledge and is a skilled surgeon, I felt that he could improve on the communication front. Sometimes, it seemed like he was in a rush and didn''t fully explain the treatment plan or answer my questions. However, he did provide effective treatment, and I am satisfied with the outcome.'),
	 (2000000170,2000000056,2000000086,1,'I would rate Doctor Williams a 1. My experience was very disappointing, as the doctor showed little empathy, had poor time management skills, and provided poor treatment overall.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000171,2000000056,2000000087,4,'I would rate Dr. Williams a 4 out of 5. The doctor has a pleasant personality and a good listening skill. The effectiveness of the treatment is excellent, and he makes sure to answer all of my questions. However, there are times when he is a bit slow in responding, and sometimes his staff has to remind him of certain details I had previously mentioned.'),
	 (2000000172,2000000057,2000000080,5,'I would rate Dr. Patterson a 5 out of 5. She has been very thorough, professional, and compassionate in addressing my needs. She is a fantastic healthcare provider and I am fortunate to have her expertise on my team.'),
	 (2000000173,2000000057,2000000081,4,'Dr. Patterson is a highly charismatic physician who puts his patients at ease immediately. As a general practitioner, he is well-versed in a wide range of medical issues, which makes him an excellent diagnostician. Although his treatment plan can sometimes be a bit aggressive, it is often effective in providing long-term relief. Overall, I highly recommend Dr. Patterson, and would rate both the physician and the experience 4 out of 5.'),
	 (2000000174,2000000057,2000000087,3,'I rate Dr. Patterson as a 3 out of 5. The positive aspects of my experience were his charisma and his effectiveness in treating my condition. However, the wait time for appointments was often lengthy, which negatively impacted the overall experience.'),
	 (2000000175,2000000058,2000000081,2,'2/5. Dr. Long is an experienced physician, but I had some concerns during the consultation about his communication skills and efficiency. During the examination, he seemed focused and knowledgeable, however, I felt like he could have spent more time explaining some of his recommendations. His staff was helpful and courteous.'),
	 (2000000176,2000000058,2000000082,4,'I would rate my experience with Doctor Long a 4/5. Doctor Long''s charismatic personality and their effective treatment approach made me feel comfortable during my appointments. However, I sometimes felt that the time spent with him could have been more efficient to ensure adequate attention to my concerns.'),
	 (2000000177,2000000058,2000000087,5,'I would rate my experience with Doctor Long a 5, as she is a very charismatic doctor and provided excellent guidance. The treatment plan she developed for my specific condition was tailored to my individual needs and was very effective. Furthermore, she managed to balance the quality of care with the efficiency of the process, making the whole experience smooth and comfortable.'),
	 (2000000178,2000000059,2000000082,5,'As a patient of Dr. Dunn, I would rate my experience with him as a 5 out of 5. He is a highly charismatic and compassionate healthcare provider who takes the time to thoroughly explain and answer my questions, providing me with a personalized and proactive approach to my care. Dr. Dunn''s expertise, combined with his genuine care and communication skills, has resulted in my improved overall health and well-being.'),
	 (2000000179,2000000059,2000000083,2,'2/5. Doctor Dunn was very charismatic and made me feel at ease during my appointment. Unfortunately, their time management skills need improvement, as I spent over an hour waiting in their office before being seen. The effectiveness of the treatment could be improved, as I am still experiencing the same symptoms after my visit.'),
	 (2000000180,2000000059,2000000084,2,'I rate Doctor Dunn a 2. He''s a charismatic figure, but his time management skills are not as efficient as they could be, often leaving me waiting for long periods of time.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000181,2000000060,2000000081,4,'I would rate my experience with Doctor Ellis a 4 out of 5. While I have been impressed by the doctor''s knowledge and experience, there have been some instances where I felt he could improve his communication skills. However, he has always been willing to answer any questions or concerns I may have. The effectiveness of the treatment itself has been very effective and satisfactory.'),
	 (2000000182,2000000060,2000000084,4,'I have been seeing Dr. Ellis for over a decade for various medical issues, and have consistently been met with high-quality care. Dr. Ellis has a genuine concern for his patients'' well-being and consistently takes time to answer any questions or concerns. His professionalism and expertise have kept me and my loved ones in good health for many years. I highly recommend him. 4/5 stars'),
	 (2000000183,2000000060,2000000088,5,'I would rate Dr. Ellis a 5 out of 5. He has a wonderful bedside manner, is incredibly knowledgeable, and takes the time to answer any questions you may have. He has helped me manage my chronic migraines, and has improved my quality of life.'),
	 (2000000184,2000000061,2000000080,5,'I would rate my experience with Doctor Parsons as a 5. She has a very charismatic personality and was excellent in delivering the treatment plan effectively. The time she spent with me during consultations was well-managed, and I never felt rushed. She is highly experienced and knowledgeable in her field, which made me feel confident in her care.'),
	 (2000000185,2000000061,2000000084,2,'I would rate my experience with Dr. Parsons as a 2. While I appreciate her efforts to find a solution for my medical issue, I feel that her communication skills and approach to treatment could be more effective. I would like to have a clearer understanding of the plan she has for my care, and I think she could work on being more empathetic and patient with her approach. Additionally, I felt some delays in the treatment process that could have been addressed for better overall care.'),
	 (2000000186,2000000061,2000000087,4,'I rate Doctor Parsons a 4. I appreciate his charisma and the effectiveness of the treatment; however, I feel that the time management could be improved.'),
	 (2000000187,2000000062,2000000080,2,'2/5. I had a difficult time communicating with Doctor Thompson; he seemed disinterested in my concerns and barely took the time to explain anything. Additionally, I often had to wait in long lines for appointments and felt like the treatment itself was lacking in effectiveness.'),
	 (2000000188,2000000062,2000000082,5,'I would rate my experience with Doctor Thompson as a 5. He is a highly charismatic physician, with a great sense of humor and an approachable demeanor, which made me feel immediately at ease. He was also very effective in explaining complex medical concepts in simple terms, making it easy for me to follow and understand the treatments he recommended.'),
	 (2000000189,2000000062,2000000086,4,'I would rate my experience with Doctor Thompson a 4 out of 5. Doctor Thompson is a charismatic and knowledgeable physician, making it easy to open up about my health concerns. They were effective in diagnosing and treating my medical condition, and I appreciate the time they took to answer my questions. The only room for improvement would be in regards to the wait time for appointments.'),
	 (2000000190,2000000063,2000000086,4,'Dr. Lewis is an exceptional doctor with a high level of charisma and excellent treatment skills.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000191,2000000063,2000000087,3,'I would rate my experience with Doctor Lewis a 3. The doctor has a strong presence and is very charismatic. He took the time to thoroughly explain my condition and listened attentively to my concerns. However, there were some minor issues with time management during my appointments which slightly affected the overall experience.'),
	 (2000000192,2000000063,2000000088,3,'I would recommend Doctor Lewis, although the experience was not perfect. The treatment effectiveness was satisfactory. Time management could have been improved, as some appointments were run tardily.'),
	 (2000000193,2000000064,2000000080,4,'I would rate Doctor Rose a 4. My experience with her was positive, but there were a few areas of improvement. She is a very charismatic physician, which made me feel comfortable during our interactions. However, I did feel that the time she spent with me was limited, and there could be more effective communication regarding my treatment plan.'),
	 (2000000194,2000000064,2000000084,2,'2/5. Although I appreciate Dr. Rose''s knowledge and experience, I feel there could be improvements in communication and efficiency during appointments. I often had to wait longer than expected, and sometimes had difficulty understanding certain aspects of her explanations.'),
	 (2000000195,2000000064,2000000086,3,'Doctor Rose has a rating of 3. Although she is a very charismatic physician, I feel that her communication skills could benefit from improvement. On multiple occasions, she seemed to misunderstand my concerns, which made it difficult for me to feel comfortable discussing my health issues with her. Additionally, the effectiveness of the treatment I received under her care was not consistent, and I had to constantly advocate for myself to ensure optimal care.'),
	 (2000000196,2000000065,2000000080,5,'5/5. Excellent doctor! Dr. Cardenas'' bedside manner is superb - he is very patient, compassionate, and always makes me feel at ease during my appointments. He spends the necessary time to understand my health concerns and provides me with comprehensive explanations, so I can make informed decisions about my care. Additionally, his treatment plan has been extremely effective, and I have been feeling much better.'),
	 (2000000197,2000000065,2000000082,4,'Dr. Cardenas is a very competent doctor who takes good care of his patients. He is professional, personable and has a great bedside manner. I would rate my experience with him a 4.'),
	 (2000000198,2000000065,2000000083,3,'I would rate my experience with Dr. Cardenas a 3. While he is a very charismatic physician and has a great bedside manner, I feel he could be more effective in managing the time of his patients to provide more personalized care. The wait times in the office were sometimes lengthy, which made it difficult to schedule follow-up visits or discuss more complex health concerns.'),
	 (2000000199,2000000066,2000000080,4,'I''d rate Dr. Wallace a 4 out of 5. Although he has great charisma and is highly effective in treating patients, he could improve time management skills to provide more personalized care.'),
	 (2000000200,2000000066,2000000082,3,'3/5 - While Dr. Wallace is an expert in his field, there were certain aspects of his practice that could improve. I had a difficult time communicating with him during my appointments, and sometimes I felt that he was not as attentive as I would have hoped. Additionally, the waiting time in his office was often longer than I had anticipated, which added to my overall experience.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000201,2000000066,2000000083,1,'Really bad experience. Long waiting times and bad attention.'),
	 (2000000202,2000000067,2000000080,5,'I''ve had the pleasure of working with Dr. Davis in the past and would rate him a 5/5. His charismatic personality made him a great communicator and he was very effective in providing treatment. Additionally, he always made sure to allocate enough time for his patients.'),
	 (2000000203,2000000067,2000000081,3,'I would rate my experience with Dr. Davis as a 3. While Dr. Davis is a highly charismatic physician, the effectiveness of the treatment and her time management could be improved.'),
	 (2000000204,2000000067,2000000088,3,'I rate Doctor Davis as a 3. Although I found him to be charismatic and knowledgeable during our interactions, his time management was sometimes challenging, resulting in longer wait times for me.'),
	 (2000000205,2000000068,2000000080,5,'My experience with Dr. Adams as a patient, I would rate a 5/5. Dr. Adams is a very charismatic, knowledgeable, and effective physician. He takes the time to listen to his patients and provides clear explanations of medical concepts. Additionally, he has a strong track record of successful treatment.'),
	 (2000000206,2000000068,2000000085,5,'I rate Dr. Adams as a 5. He is a very charismatic doctor, and I feel he has a great understanding of my medical concerns. He takes his time to thoroughly examine me, answers all my questions and concerns, and provides personalized treatment plans tailored to my specific needs. I would highly recommend him to anyone looking for an exceptional healthcare professional.'),
	 (2000000207,2000000068,2000000088,3,'My experience with Dr. Adams was satisfactory overall, with a rating of 3. Dr. Adams has a great personality and is very charismatic, which made me feel comfortable during appointments. However, I did feel that the wait times in the office were a bit long, which could be improved. As for my treatment, I was happy with the effectiveness of the treatment plan she prescribed for me, but I did feel that some appointments could have been more efficient.'),
	 (2000000208,2000000069,2000000080,4,'My experience with Doctor Allison was exceptional. She has a very warm and inviting personality, making each appointment feel like a visit with a friend. In terms of effectiveness, she is an excellent practitioner who takes the time to listen to her patients and provides thorough explanations. I appreciate her professionalism and expertise. One area of improvement that I can suggest is the wait time at the clinic.'),
	 (2000000209,2000000069,2000000082,4,'I would rate Doctor Allison a 4/5. Her charisma and communication skills were excellent, and she effectively managed my medical concerns. However, I felt that some aspects of my treatment could have been more efficient.'),
	 (2000000210,2000000069,2000000085,5,'Dr. Allison is a 5-star physician. Her professionalism, knowledge, and communication skills create a comfortable and confident environment. As a highly qualified medical professional, Dr. Allison provides exceptional care with a high standard of efficiency, ensuring that each patient receives the highest level of care. She is an excellent doctor.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000211,2000000070,2000000085,3,'5 (exceptional) - Dr. Graves is a highly gifted physician with a charismatic personality who effectively treats his patients. I had the privilege to receive excellent care from Dr. Graves during a recent illness, where he demonstrated excellent clinical judgement and provided timely assistance, all with a reassuring and compassionate demeanor. I highly recommend Dr. Graves to anyone seeking quality medical care.'),
	 (2000000212,2000000070,2000000086,3,'I would rate my experience with Dr. Graves a 3 out of 5. While he was very knowledgeable and had great bedside manner, he seemed to be a bit dismissive of my concerns and questions. I felt like his priority was to rush through patients rather than giving each patient the individualized care he claimed to provide. Additionally, the wait times were long, and I often felt like I was not being listened to or taken seriously.'),
	 (2000000213,2000000070,2000000087,4,'I would rate my experience with Doctor Graves as a 4. The doctor has a strong presence and a clear sense of purpose, making it easy to approach them with any concerns. They took the time to understand my medical history and provided me with effective treatments, addressing both my symptoms and underlying conditions. Their availability and communication throughout my appointments left me feeling confident in their care.'),
	 (2000000214,2000000071,2000000084,4,'4/5. Dr. Villa''s bedside manner and approach to treatment exceeded my expectations, keeping me well-informed and addressing my concerns. I appreciated the time she took to answer my questions, and the personalized treatment plan she developed for me.'),
	 (2000000215,2000000071,2000000085,2,'I rate my experience with Doctor Villa as a 2. While he is knowledgeable, I found his communication lacking during my appointment. He seemed rushed and didn''t take enough time to address my concerns.'),
	 (2000000216,2000000071,2000000087,5,'I rate Dr. Villa a 5/5. She is a highly charismatic and knowledgeable doctor, and the effectiveness of her treatment has been excellent. However, there were a couple of instances where her time management could use improvement. Overall, I highly recommend her as a doctor.'),
	 (2000000217,2000000072,2000000080,5,'Exceptional Doctor Dawson is an exceptional Physician. His knowledge and expertise in the field of medicine is outstanding, and he consistently provides excellent care to his patients. He is highly charismatic and has an excellent bedside manner that puts patients at ease. Additionally, he is very effective and efficient in his work, and always strives to provide top-notch treatment.'),
	 (2000000218,2000000072,2000000082,5,'Dr. Dawson is an excellent physician! He has been my primary healthcare provider for over 10 years, and I cannot say enough positive things about him. He is a highly skilled doctor who is knowledgeable in multiple fields, including cardiology, orthopedics, and neurology. Dr. Dawson has a great bedside manner, always taking the time to address my concerns and answer my questions, making me feel very comfortable during our interactions. '),
	 (2000000219,2000000072,2000000086,4,'I would rate my experience with Dr. Dawson as a 4 out of 5. His charisma and effectiveness in treating my condition made for a great experience, but I did feel that the time spent with him was sometimes limited.'),
	 (2000000220,2000000073,2000000081,2,'I rate Doctor Johns a 2/5. While the doctor has a high level of charisma and is very effective at treating patients, their poor time management and unorganized workflow negatively impacted my overall experience.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000221,2000000073,2000000083,5,'5 stars across the board! Doctor Johns is an excellent physician. Their charisma and approach to treatment is spot on, and their effectiveness in managing my condition is top notch. The time they take to address my concerns and answer my questions is also commendable. Overall, a great experience!'),
	 (2000000222,2000000073,2000000087,4,'Dr. Johns is a highly charismatic physician, who effectively diagnoses and treats a wide range of medical conditions. His communication skills, bedside manner, and willingness to take the time to explain procedures and answer questions are highly commendable. On a scale of 1 to 5, with 5 being the highest, I would rate Dr. Johns a 4.'),
	 (2000000223,2000000074,2000000081,2,'I would rate my experience with Doctor Johnson as a 2. Although he has a strong presence and provides a comprehensive diagnosis, his communication style could use improvements. I often felt unsure about the next steps in my treatment and could have benefitted from more straightforward explanations.'),
	 (2000000224,2000000074,2000000084,2,'I would rate my experience with Doctor Johnson as a 2 out of 5. Although Doctor Johnson has a friendly and approachable personality, their approach to treating my condition seemed unprofessional and ineffective. The appointments were often disorganized, and I frequently had to wait for long periods. Furthermore, their knowledge and expertise in the medical field seemed limited.'),
	 (2000000225,2000000074,2000000086,2,'I would rate Doctor Johnson a 2 out of 5. While he was charismatic and seemed very knowledgeable, I found his approach to be more focused on prescription quantity instead of individual patient treatment. The time management in terms of waiting room and appointment scheduling seemed disorganized, making it a difficult overall experience.'),
	 (2000000226,2000000075,2000000080,3,'I would rate the encounter with Doctor Yoder a 3. Doctor Yoder''s communication skills and overall kindness were excellent, but the treatment itself was not as effective as I would have hoped. The time management during the appointment was a bit disorganized, resulting in a longer wait time than I expected, despite being a priority patient.'),
	 (2000000227,2000000075,2000000082,4,'Dr. Yoder has been an excellent provider throughout my medical journey. He always takes the time to answer my questions, provides clear explanations of medical procedures, and has a genuine concern for my well-being. I would highly recommend him to any person seeking a knowledgeable, compassionate, and effective healthcare professional.'),
	 (2000000228,2000000075,2000000084,5,'5 - Excellent - Doctor Yoder is an experienced and skilled physician who listens to my concerns, provides helpful advice, and thoroughly explains treatment options. He takes the time to answer my questions and addresses my concerns, leaving me feeling confident in his abilities.'),
	 (2000000229,2000000076,2000000081,3,'As a physician assistant, there are several factors I considered when rating my experience with Dr. Mcgee. I rated him a 3 for his charisma as he was approachable, friendly, and had a great bedside manner. His effectiveness of treating patients was also a 3, as he was knowledgeable in medical procedures and provided efficient care. However, there were some areas that could have been improved, such as the communication regarding test results and follow-up appointments.'),
	 (2000000230,2000000076,2000000083,2,'I would rate Dr. Mcgee a 2 out of 5. Although he was very charismatic and had excellent communication skills, I did not feel he provided effective treatment for my medical concerns. The wait times in his office were often long, and I often felt like a number rather than a valued patient. Additionally, there seemed to be a lack of continuity in care, and I frequently had to request tests and referrals to other specialists.');
INSERT INTO ratings (rating_id,doctor_id,patient_id,rating,comments) VALUES
	 (2000000231,2000000076,2000000087,4,'I would rate my experience with Doctor Mcgee a 4. The doctor has a strong presence and a calm demeanor, making one feel reassured during the consultation. Additionally, they took the time to thoroughly explain various medical conditions and treatment options in simple terms. However, I did feel that the appointment could have been more efficient; it seemed like there was a delay in the lab results which added to the length of the visit.'),
	 (2000000232,2000000077,2000000083,5,'5 - Doctor West is an excellent physician with a high level of professional expertise, charisma, and excellent clinical skills. She takes the time to listen to my concerns, explains complex medical issues simply, and provides personalized treatment plans that are tailored to my unique needs. I highly recommend her to anyone seeking medical care.'),
	 (2000000233,2000000077,2000000084,5,'I rate Doctor West a 5. They have a great bedside manner, making me feel comfortable and explaining everything clearly. Their treatment plan is effective and tailored to my specific needs, and I''m grateful for their help.'),
	 (2000000234,2000000077,2000000087,5,'I would rate Dr. West a 5 out of 5. He has been very thorough throughout my treatment, demonstrating excellent knowledge and skills in his field. His charismatic personality makes him an excellent doctor, and his treatment plans have been highly effective in helping me manage my condition. I appreciate Dr. West''s time and expertise, and would highly recommend him to anyone seeking his care.'),
	 (2000000235,2000000078,2000000084,2,'I would rate my experience with Doctor Brown as a 2. Although he has excellent knowledge and communication skills, I feel his time management could be improved. I had to wait in the examination room for a long time, and it seemed like the doctor was rushing through each patient.'),
	 (2000000236,2000000078,2000000085,2,'I would rate Doctor Brown a 2. My experience with him was mixed, as he has a pleasant demeanor and is knowledgeable in his field. However, I felt that his communication skills could improve, and there were instances where he was not as attentive to my concerns as I would have liked.'),
	 (2000000237,2000000078,2000000088,3,'I would rate my experience with Doctor Brown a 3. Doctor Brown is an excellent physician, but there were some areas where I felt that he could improve. Although he has a charismatic and confident demeanor, his communication skills could benefit from refinement. Additionally, while the treatment he provided was effective, I sometimes felt like my concerns were secondary to other priorities.'),
	 (2000000238,2000000079,2000000080,2,'My experience with Doctor Merritt was satisfactory but not exceptional. Although he has a calm demeanor and is a skilled physician, his bedside manner could improve. I often had to wait longer than I would have liked, and sometimes felt rushed during our appointments. The effectiveness of the treatment he recommended was satisfactory, however, and I appreciate that he always took the time to answer my questions.'),
	 (2000000239,2000000079,2000000081,4,'Doctor Merritt is a highly skilled and experienced physician. The treatment plan tailored to my needs has been effective, and he takes the time to thoroughly answer my questions.'),
	 (2000000240,2000000079,2000000084,4,'I would rate my experience with Doctor Merritt a 4 out of 5. I found him to be a knowledgeable and competent doctor, as well as a great communicator. His expertise and experience in sports medicine made me feel comfortable with the care he provided. However, I did have to wait longer than I would have liked for my appointments, which was a slight drawback.');
